#!/usr/bin/env bash
#Installs ngnix on server
sudo apt-get update
sudo apt-get install -y ngnix
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.ngnix-debian.html
sudo service ngnix start

