#!/usr/bin/env bash
#A script that displays "Best School" 10 times, but on 9 "Hi"

Phrase1="Best School"
Phrase2="Hi"

count=0

while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]; then
		echo "$phrase2"
	else
		echo "$phrase1"
	fi 
	((count++))
done
