#!/usr/bin/env bash
#A script that displays "Best School" 10 times, but on 9 "Hi"

count=0
while [ $count -lt 11 ]
do
    if [ $count = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count+=1))
done
