#!/usr/bin/env bash
#A script that loops "Best School", but on 4 = "bad luck"; 8 = "good luck"

count=1
while [ $count -lt 11 ]
do
    if [ $count = 4 ]
    then
        echo "bad luck"
    elif [ $count = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    let count+=1
done
