#!/usr/bin/env bash
#A script that loops "Best School", but on 4 = "bad luck"; 8 = "good luck"

phrase1="Best School"
phrase2="bad luck"
phrase3="good luck"

count=0
while [ $count -lt 11 ]
do 
	if [ $count = 4 ]
	then 
		echo "$phrase2"
	elif [ $count = 8 ]
	then
		echo "$phrase3"
	else
		echo "$phrase1"
	fi 
	let count+=1
done
