#!/usr/bin/env bash
#A script that displays numbers from 1 to 20, and numbers that are bad luck in other countries

count=1
while [ $count -lt 21 ]
do 
	case $count in 

		4)
			echo $count
			echo "bad luck from China"
			;;

		9)
			echo $count
			echo "bad luck from Japan"
			;;

		17)
			echo $count
			echo "bad luck from Italy"
			;;

		*)
			echo $count
			;;
	esac

	((count+=1))
done
