#!/usr/bin/env bash
#A script that gives you information about the school file

phrase1="school file does not exist"
phrase2="school file is not empty"
phrase3="school is regular file"
phrase4="school file exist"

file="school"

if [ -e "$file" ]
then
	echo "school file exists"
	if [ ! -s "$file" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$file" ]
	then
		echo "school is regular file"
	fi 
else
	echo "school file does not exist"
fi
